- .cargo/config.toml
- .clippy.toml
- .github/workflows/ci.yml
- Cargo.toml
- rustfmt.toml
- src/block.rs
- src/block_test.rs
- src/core.rs
- src/core_test.rs
- src/hash.rs
- src/hash_test.rs
- src/lib.rs
- src/serde_utils.rs
- src/serde_utils_test.rs
- src/state.rs
- src/state_test.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/1)
> Import initial code

- src/block.rs
- src/core.rs
- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/3)
> Add StateUpdate and move GlobalRoot to core

- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/7)
> Implement felt to usize conversion.

- .github/workflows/ci.yml
- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/8)
> Add docs to ci and fix doc of ContractAddress

- src/serde_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/10)
> Fix clippy new version error.

- Cargo.toml
- src/hash.rs
- src/hash_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/5)
> Use xJonathanLEI/starknet-rs to compute stark hash

- src/serde_utils.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/9)
> Change contract_address to sender_address in InvokeTransaction.

- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/13)
> Impl. `TryFrom<StarkFelt>` for `EthAddress`.

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/14)
> Rename CallData -> Calldata (to fit snake case calldata).

- src/hash.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/15)
> Move `impl TryFrom<StarkFelt> for EthAddress` next to struct definition.

- src/block.rs
- src/core.rs
- src/state.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/11)
> Remove implementations of defaults

- src/core.rs
- src/core_test.rs
- src/hash.rs
- src/hash_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/19)
> Rename shash and patky macros.

- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/20)
> Default for EntryPointType.

- src/transaction.rs
Macro for succinct creation of Calldata. Usage examples:
calldata![]
calldata![stark_felt!(1), stark_felt!(2), stark_felt!(3)]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/21)
> Create calldata! macro.

- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/16)
> Restore default definitions.

- src/block.rs
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/23)
> Fix the display of Felt, add display to BlockHash

- src/core.rs
- src/core_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/22)
> Add test to calculate_contract_address.

- src/core.rs
- src/serde_utils.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/24)
> Derive Display in hashes

- .github/workflows/ci.yml
- Cargo.toml
- src/api_core.rs
- src/api_core_test.rs
- src/block.rs
- src/block_test.rs
- src/hash.rs
- src/hash_test.rs
- src/lib.rs
- src/serde_utils.rs
- src/state.rs
- src/state_test.rs
- src/transaction.rs
- src/with_std.rs
- src/without_std.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/26)
> feat: introduce no_std support

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/32)
> Add from_address field to MessageToL1 struct.

- src/core.rs
- src/deprecated_contract_class.rs
- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/37)
> Add sierra contract class again

- src/core.rs
- src/deprecated_contract_class.rs
- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/38)
> Add Sierra ContractClass

- src/core.rs
- src/deprecated_contract_class.rs
- src/lib.rs
- src/state.rs
- src/state_test.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/40)
> Yair/sn 0.11

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/44)
> Add getters

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/55)
> Create implement_invoke_tx_getters! macro.

- Cargo.toml
- src/state.rs
(As a temporary solution)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/59)
> Copy ThinSteaDiff from papyrus_storage crate to be used in blockifier crate.

- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/60)
> Copy ThinStateDiff impl from StateDiff (both in starknetAPI now).

- src/core_test.rs
- src/hash.rs
- src/hash_test.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/63)
> From<Fee> for StarkFelt

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/65)
> Bump cairo_lang_version

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/67)
> Add paid_fee_on_l1 field to L1HandlerTransaction.

- src/core_test.rs
- src/hash.rs
- src/lib.rs
- src/transaction.rs
- src/type_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/66)
> Generic uint->X converter

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/69)
> Revert paid_fee_on_l1 addition.

- Cargo.toml
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/70)
> Replace web3 with primitive-types

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/71)
> Update cairo-lang-starknet revision.

- src/deprecated_contract_class.rs
- src/serde_utils.rs
- src/serde_utils_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/73)
> Deserialize junk ABI as None

- src/deprecated_contract_class.rs
- src/serde_utils.rs
- src/serde_utils_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/74)
> Fix ABI deserialization

- Cargo.lock
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/77)
> Align starknet-crypto dependency.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/80)
> Add package metadata

- Cargo.lock
- Cargo.toml
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/81)
> Add package description

- .cargo/config.toml
- .clippy.toml
- src/hash.rs
- src/hash_test.rs
Used to extract integers from felts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/87)
> Add TryFrom<StarkFelt> for u64.

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/90)
> Invoke transaction v0 fix

- Cargo.lock
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/92)
> Bump version to 0.2.0

- Cargo.lock
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/99)
> Bump Cairo version

- src/deprecated_contract_class.rs
- src/state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/102)
> Change serialization of EntryPointOffset to hex.

- src/block.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/100)
> add transaction execution status enum

- src/block.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/103)
> Move tx hash from txs to BlockBody

- src/core.rs
- src/core_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/104)
> Utility macros for tests

- src/deprecated_contract_class.rs
- src/serde_utils_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/107)
> Add an optional state mutability field to FunctionAbiEntry.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/109)
> chore(release): bump version to 0.3.0

- src/core.rs
- src/core_test.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/97)
> Move EthAddress to core and serde it without leading zeroes.

- Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/110)
> Updating the new SN_API version in Cargo.lock

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/106)
> Export max_fee, nonce and signature to AccountParams struct

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/111)
> Adding new structs for transaction V3

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/108)
> Adding transaction V3

- src/deprecated_contract_class.rs
- src/serde_utils_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/113)
> feat(deprecated_contract_class)!: add type to EventAbiEntry and StructAbiEntry

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/112)
> Add serde flattern attribute to account_params fields.

- Cargo.lock
- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/115)
> chore(release): bump version

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/117)
> Revert of commit hashes: fe16f8c, 5e642b3, 498386c, d4b7d91, d34e997 (AccountParams and V3 changes).

- src/deprecated_contract_class.rs
Fixes #121
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/122)
> make debug_info optional

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/136)
> Release version 0.5.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/137)
> Release 0.5.0-rc1

- .github/workflows/ci.yml
- rust-toolchain.toml
- rustfmt.toml
- scripts/rust_fmt.sh
- src/serde_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/140)
> Remove nightly version

- src/block.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/138)
> Add missing commitments to the block struct.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/143)
> Tag new version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/147)
> Release version 0.6.0-rc0

- src/block.rs
This reverts commit df6a9b84f8a86c51880a1e762b2d0acb195323fe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/148)
> revert: add missing commitments to the block struct. (#138)

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/152)
> Release 0.6.0-rc2: Bump cairo-* to 2.4.0-rc2

- src/block.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/151)
> Add ExecutionResources to transaction output

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/154)
> Fix serialization of Builting::SegmentArena

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/160)
> Merge: Release 0.6.0-rc3

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/162)
> Stabilize 0.6.0 - remove rc from version

- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/165)
> feat(hash): add Poseidon hash

- src/block.rs
- src/block_test.rs
- src/core.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/134)
> feat(block): block signatures

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/167)
> update cairo-lang-starknet dep to 2.5.0-dev.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/168)
> chore(release): set version to 0.7.0-dev.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/172)
> chore: remove unused dep

- Cargo.toml
- src/block.rs
- src/core.rs
- src/data_availability.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/176)
> feat: add members of block header

- Cargo.toml
- src/deprecated_contract_class.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/177)
> chore: bump cairo lang version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/178)
> chore: bump version to 0.8.0

- src/block.rs
- src/core.rs
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/179)
> feat!: add state diff commitment

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/182)
> chore: bump version to 0.10.0-dev.0

- Cargo.toml
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/183)
> add revert reason to transaction output

- Cargo.toml
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/184)
> chore: publish v0.10.0-dev.2

- Cargo.toml
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/185)
> fix: flatten TransactionExecutionStatus in output

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/186)
> chore: bump cairo version to 2.6.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/187)
> chore: publish v0.10.0

- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/188)
> feat: derive Default for ThinStateDiff

- src/block.rs
- src/core.rs
- src/state.rs
- src/state_test.rs
- feat!: add missing fields to BlockHeader
- feat: add len to ThinStateDiff
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/191)
> feat: add len to ThinStateDiff

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/193)
> chore: publish v0.11.0

- src/state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/194)
> fix: fix documentation

- src/transaction.rs
See use case: https://reviewable.io/reviews/starkware-libs/mempool/5#-NtLOapJ3XCnI-DBbRyM
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/195)
> chore: add version method to transaction

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/205)
> chore: bump version to new dev version

- Cargo.toml
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/211)
> feat: swap pedersen implementation

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/215)
> chore: bump dev version

- src/data_availability.rs
- src/external_transaction.rs
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/220)
> feat(transaction): implement external transactions

- Cargo.toml
- src/external_transaction.rs
- src/external_transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/224)
> test(transaction): test external transaction

- src/internal_transaction.rs
- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/227)
> feat(transaction): implement internal transactions

- src/data_availability.rs
- src/external_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/228)
> refactor: some cosmetic changes for external transactions

- src/internal_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/229)
> feat(transaction): derive clone for internal transaction

- Cargo.toml
- src/external_transaction.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/225)
> Mohammad/transaction/transaction converters/add tx hash

- src/internal_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/232)
> Add getters for contract address and nonce in internal transaction

- src/internal_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/233)
> Add Eq and PartialEq to InternalTransaction

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/235)
> make TransactionHasher public

- src/internal_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/238)
> Add a tx_hash getter for internal transaction

- src/internal_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/239)
> Add a tip getter for internal transaction

- src/external_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/234)
> feat: add ref getters for external transaction

- src/block_hash.rs
- src/block_hash/event_hash.rs
- src/block_hash/event_hash_test.rs
- src/block_hash/utils.rs
- src/crypto.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/240)
> Use HashChain for event hash

- src/crypto/patricia_hash.rs
- src/crypto/patricia_hash_test.rs
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/216)
> feat!: use poseidon hash in patricia hash tree

- src/block_hash.rs
- src/block_hash/transaction_commitment.rs
- src/block_hash/transaction_commitment_test.rs
commit-id:094d898f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/241)
> feat: calculate transaction commitment root

- src/block_hash.rs
- src/block_hash/receipt_commitment.rs
- src/block_hash/receipt_commitment_test.rs
- src/transaction.rs
Calculations for the receipt hash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/242)
> Yoav/block hash/receipt hash

- src/block_hash.rs
- src/block_hash/state_diff_hash.rs
- src/block_hash/state_diff_hash_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/243)
> feat: calculate state diff hash

- Cargo.toml
- src/block_hash/receipt_commitment.rs
- src/block_hash/receipt_commitment_test.rs
- src/hash.rs
- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/244)
> fix: wrap revert reason with a keccak

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/253)
> chore: version update

- src/block_hash/state_diff_hash.rs
- src/block_hash/state_diff_hash_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/252)
> fix: sort elements before hashing

- src/block_hash/state_diff_hash.rs
- src/block_hash/state_diff_hash_test.rs
- src/crypto/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/256)
> feat: filter out a contract with empty storage maps

- src/external_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/255)
> feat: add tip and nonce getter for external transaction

- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/254)
> feat: add TryFrom<StarkFelt> for u128

- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/261)
> feat: add TryFrom<StarkFelt> for u32

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/265)
> chore: version update to 0.13.0-dev.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/266)
> chore: bump cairo-lang-starknet-classes dependency version

- Cargo.toml
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/267)
> chore: bump starknet-types-core dependency version

- Cargo.toml
- src/block_hash/block_hash_calculator_test.rs
- src/block_hash/event_commitment_test.rs
- src/block_hash/receipt_commitment_test.rs
- src/block_hash/state_diff_hash_test.rs
- src/block_hash/transaction_commitment_test.rs
- src/block_test.rs
- src/core_test.rs
- src/crypto/crypto_test.rs
- src/crypto/patricia_hash_test.rs
- src/external_transaction_test.rs
- src/hash.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/270)
> feat: explicit object/trait imports for felt macro

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/271)
> chore: version update to 0.13.0-dev.4

- Cargo.toml
- src/block_hash/block_hash_calculator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/272)
> feat: add derive features

- src/block_hash/block_hash_calculator.rs
- src/block_hash/event_commitment.rs
- src/block_hash/event_commitment_test.rs
- src/block_hash/transaction_commitment.rs
- src/block_hash/transaction_commitment_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/276)
> fix: rename fields to singular form

- src/block.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/281)
> fix: Make state_diff_commitment non option

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/283)
> chore: bump starknet-types-core version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/287)
> Bump version to `0.13.0-dev.8`.

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/280)
> feat: add new 0.13.2 builtins

- src/block.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/289)
> fix: make transaction and event commitments non optional

- src/block.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/291)
> fix: make all header commitments optional

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/292)
> chore: bump version to 0.13.0-dev.9

- src/rpc_transaction.rs
- src/rpc_transaction_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/285)
> refactor: use small letters for rpc transaction enum

- src/transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/290)
> chore: derive enum-iter for builtin enum

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/294)
> chore: bump version to RC
