Cargo.toml
src/transaction.rs

I checked manually that it (de)serializes exactly as it did without the Rc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/12)

Rc the vector inside CallData.

---

Cargo.toml
src/core.rs

I compared the output to a contract address calculated similarly in cairo code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/17)

Add calculate_contract_address_from_hash.

---

src/lib.rs
src/state.rs
src/state_test.rs

- In new releases offsets will be numbers, whereas in the past they were
strings.
- Simplified casting logic.
- Remove `serde from=` since it isn't relevant.
- Added a test for the `into` case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/33)

Allow `EntryPointOffset` to be serde'd from int/string

---

Cargo.toml
src/deprecated_contract_class.rs
src/hash.rs

This is necessary to properly implement: https://github.com/starkware-libs/blockifier/pull/423
It enables conversion of Cairo 1.0 casm artifacts into the blockfier representation such that they can be executed by blockifier
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/52)

Implement TryFrom<CasmContractEntryPoint> for EntryPoint

---

src/transaction.rs

It's useful to have this kind of wrapper type implement `Form`
```rust
#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, PartialOrd, Ord)]
pub enum DeclareTransaction {
V0(DeclareTransactionV0V1),
V1(DeclareTransactionV0V1),
V2(DeclareTransactionV2),
}
```
Because V0 and V1 are internally the same types, it is not possible to derive `From` on this enum. Which is a bit weird. Did you consider something like this:
```rust
pub enum DeclareTransaction {
V0V1(DeclareTransactionV0V1),
V2(DeclareTransactionV2),
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/48)

feat(transaction): derive  for transaction version wrapper enum types

---

src/deprecated_contract_class.rs

When deserializing a "deprecated" Cairo contract class using the starknet-api and compiling with starknet-compile version 0.11, the deserializer expects the value of the "type" attribute of the ABI schema for functions to be "regular". However, the JSON output of the Cairo program compilation contains an ABI schema with the entry type being "function". This causes the deserialization to fail when trying to read a Cairo contract class.
This PR provides a fix to this issue by changing the default value expected in FunctionAbiEntryType to "function" instead of "regular".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/50)

Fix: default serialization for FunctionAbiEntryType

---

src/core.rs
src/core_test.rs

Incrementing the maximum value in the field is 0.
Since this isn't good behavior for a nonce value, incrementing the maximum value is not allowed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/142)

Add nonce increment

---

src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/144)

add serialize and deserialize functions for ResourceBounds struct

---

Cargo.toml

Looks like `genco = 0.17.7` from last month breaks compilation. This is a dependency of `cairo-lang-starknet`, which is why we need the cargo-udeps flag (it isn't used inside starknet-api at all).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/145)

Workaround `genco` bug

---

.github/workflows/ci.yml

We are already using these versions on some of the tasks here, this is just for consistency across the different tasks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/146)

Bump action versions on CI for consistency

---

Cargo.toml

`genco` fixed the buggy 0.17.7 3 hours ago in version 0.17.8.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/149)

Release 0.6.0-rc1: includes revert of `Block` changes + fix `genco`

---

Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/158)

Fixate parity_scale_codec on 3.6.5 to fix error in udeps

---

src/crypto.rs
src/crypto_test.rs
src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/166)

feat(crypto): add crypto module with signature verification functionality

---

.gitignore
src/core.rs
src/hash.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/164)

feat: impl From<EthAddress> for StarkFelt

---

src/state.rs

Currently I can't use `ContractClass.load(...)` because the fields don't match the name. It seems to be a typo so fixing it
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/171)

fix(ContractClass): match pythonic name for entry_points_by_type

---

Cargo.toml
src/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/175)

add starknet version to header

---

src/block.rs
src/state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/189)

fix: make BlockNumber::next safe

---

Cargo.toml
src/crypto.rs
src/lib.rs
src/transaction_hash.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/204)

refactor: move transaction hash calculation to sn api

---

src/block_hash.rs
src/block_hash/event_hash.rs
src/block_hash/event_hash_test.rs
src/block_hash/utils.rs
src/hash.rs
src/internal_transaction.rs
src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/206)

feat: implement event hash

---

src/block_hash.rs
src/block_hash/block_hash_calculator.rs
src/block_hash/block_hash_calculator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/247)

feat: concat_counts into a single felt

---

src/core.rs
src/transaction_hash.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/250)

refactor: change chainid from struct to enum

---

src/block_hash/receipt_commitment.rs
src/block_hash/receipt_commitment_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/257)

fix: calculate l1 gas consumed

---

src/block_hash/block_hash_calculator.rs
src/block_hash/receipt_commitment.rs
src/block_hash/test_utils.rs
src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/260)

feat: not typed transaction output object for block hash

---

src/block.rs
src/block_hash/block_hash_calculator.rs
src/block_hash/block_hash_calculator_test.rs
src/block_hash/state_diff_hash_test.rs
src/block_hash/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/248)

feat: calculate block hash

---

src/block_hash/block_hash_calculator_test.rs
src/block_hash/state_diff_hash.rs
src/block_hash/state_diff_hash_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/262)

fix: consider replace classes as deployed contracts

---

src/external_transaction.rs
src/external_transaction_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/236)

feat(transaction): implement rpc transaction

---

src/external_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/264)

Mohammad/external tx/resource bounds/implement from trait

---

src/block_hash/block_hash_calculator.rs
src/block_hash/block_hash_calculator_test.rs
src/block_hash/receipt_commitment.rs
src/block_hash/receipt_commitment_test.rs
src/block_hash/test_utils.rs
src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/268)

feat: add l1_gas_consumed for block hash

---

src/block_hash/block_hash_calculator.rs
src/block_hash/receipt_commitment.rs
src/block_hash/test_utils.rs
src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/269)

fix: remove execution resources from block hash

---

Cargo.toml
src/block_hash/block_hash_calculator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/274)

feat: add derive features

---

src/block_hash/block_hash_calculator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/275)

test: add tests to verify block hash changes if the input change.

---

src/core.rs
src/core_test.rs
src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/279)

build: impl display for fee and contractaddress structs

---

src/block.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/282)

fix: Make n_transactions and n_events non option

---

src/transaction.rs

Add the method name to the Builtin enum.
This is connected to this request from the mempool repo: https://reviewable.io/reviews/starkware-libs/mempool/296#-O0O11mYC2gFg6AwJDAL
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/288)

feat: add name method to builtin enum

---

src/lib.rs
src/serde_utils.rs

This will mainly help test writers, who can now `assert_eq!` on `StarknetApiResult`s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starknet-api/296)

feat: add PartialEq to StarknetApiError
